apps/blog/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from django.conf.urls import url

from .views import ArchiveView
from .views import BlogDetailView
from .views import BlogsWithCategoryView
from .views import BlogListView
from .views import BlogsWithTagView
from .views import CategoriesView
from .views import TagsView

urlpatterns = [url(r"^tag/(?P<tag_name>[\w,-]+)$", BlogsWithTagView.as_view(), name="tag"),
               url(r"^category/(?P<pk>\d+)/(?P<cat_name>\w+)$", BlogsWithCategoryView.as_view(), name="category"),
               url(r"^tags$", TagsView.as_view(), name="tag_list"),
               url(r"^categories$", CategoriesView.as_view(), name="category_list"),
               url(r"^archives", ArchiveView.as_view(), name="archives"),
               url(r"^$", BlogListView.as_view(), name="home"),
               url(r"^(?P<pk>\d+)/(?P<blog_link>[\w,-]+)$", BlogDetailView.as_view(), name="blog_detail"),

               ]

urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.views.generic import TemplateView

from apps.blog.views import AboutView
from apps.blog.views import ArchiveView
from apps.blog.views import BlogsWithCategoryView
from apps.blog.views import BlogListView
from apps.blog.views import LatestPosts
from apps.blog.views import TagsView
from apps.blog.views import CategoriesView
from apps.blog.views import BlogsWithTagView
from django_blog.sitemaps import BlogSitemap, IndexSitemap

admin.autodiscover()

sitemaps = {
    'index': IndexSitemap,
    'blog': BlogSitemap,

}

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', BlogListView.as_view(), name="home"),
    url(r'^blog/', include('apps.blog.urls', namespace='blog')),
    url(r'^about$', AboutView.as_view(), name='about'),
    url(r'^404', TemplateView.as_view(template_name="404.html")),


    url(r"^tag/(?P<tag_name>[\w,-]+)$", BlogsWithTagView.as_view(), name="tag"),
    url(r"^category/(?P<pk>\d+)/(?P<cat_name>\w+)$", BlogsWithCategoryView.as_view()),
    url(r"^tags$", TagsView.as_view(), name="tag_list"),
    url(r"^categories$", CategoriesView.as_view(), name="category_list"),
    url(r"^archives", ArchiveView.as_view(), name="archives"),

    url(r'^robots.txt$', TemplateView.as_view(template_name="robots.txt", content_type="text/plain")),
    url(r'^humans.txt$', TemplateView.as_view(template_name="humans.txt", content_type="text/plain")),
    url(r'^rss/', LatestPosts(), name='feeds'),
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
]

templates/_macro/post-collapse.html
  <article class="post post-type-normal" itemscope itemtype="http://schema.org/Article">
    <header class="post-header">

      <h1 class="post-title">
        {% if post.link %}{# Link posts #}
          <a class="post-title-link post-title-link-external" target="_blank" href="{{post.get_absolute_url}}" itemprop="url">
            {{ post.title }}
          </a>
        {% else %}
            <a class="post-title-link" href="{{post.get_absolute_url}}" itemprop="url">
              {% if post.type == 'picture' %}
                {{ post.content }}
              {% else %}
                <span itemprop="name">{{ post.title}}</span>
              {% endif %}
            </a>
        {% endif %}
      </h1>

      <div class="post-meta">
        <time class="post-time" itemprop="dateCreated"
              datetime="{{post.add_time}}"
              content="{{post.add_time|date:'Y-m-d'}}" >
          {{post.add_time|date:'Y-m-d'}}
        </time>
      </div>

    </header>
  </article>

templates/_macro/post.html
{% load myapp_markup %}
<article class="post post-type-normal" itemscope="" itemtype="http://schema.org/Article">
    <header class="post-header">
        <h1 class="post-title" itemprop="name headline">
            <a class="post-title-link" href="{{post.get_absolute_url}}" itemprop="url">
                {{post.title}}
            </a>
        </h1>

        <div class="post-meta">
          <span class="post-time">
            <span class="post-meta-item-icon">
              <i class="fa fa-calendar-o"></i>
            </span>
            <span class="post-meta-item-text">发表于</span>
            <time itemprop="dateCreated" datetime="{{post.add_time}}" content="{{post.add_time|date:'Y-m-d'}}">
              {{post.add_time|date:"Y-m-d"}}
              </time>
          </span>


            <span class="post-category">
              &nbsp; | &nbsp;
              <span class="post-meta-item-icon">
                <i class="fa fa-folder-o"></i>
              </span>
              <span class="post-meta-item-text">分类于</span>

                <span itemprop="about" itemscope="" itemtype="https://schema.org/Thing">
                  <a href="{%url 'blog:category' post.category.id post.category.title%}" itemprop="url" rel="index">
                    <span itemprop="name">{{post.category}}</span>
                  </a>
                </span>

            </span>


            <span class="post-comments-count">
                &nbsp; | &nbsp;
                <a href="{{post.get_absolute_url}}#comments" itemprop="discussionUrl">
                  <span class="post-comments-count ds-thread-count"
                        data-thread-key="{{post.get_absolute_url}}"
                        itemprop="commentsCount"></span>
                </a>
              </span>


            <span id="" class="leancloud_visitors"
                  data-flag-title="{{post.title}}">
               &nbsp; | &nbsp;
               <span class="post-meta-item-icon">
                 <i class="fa fa-eye"></i>
               </span>
               <span class="post-meta-item-text">阅读次数 </span>
               <span class="leancloud-visitors-count">{{post.access_count}}</span>
              </span>

        </div>
    </header>


    <div class="post-body" itemprop="articleBody">
        {% if is_index %}
        {{post.content|slice:"0:300" | md1}}

        <div class="post-more-link text-center">
            <a class="btn" href="{{post.get_absolute_url}}" rel="contents">
                阅读全文 »
            </a>
        </div>
        {% else %}
        {{post.content | md1}}
        {% endif %}

    </div>

     <div>
      {% if not is_index %}
        {% include '_macro/wechat-subscriber.html' %}
      {% endif %}
    </div>

    <div>
      {% if not is_index %}
        {% include '_macro/reward.html' %}
      {% endif %}
    </div>

    <footer class="post-footer">
        {% if is_index %}
        <div class="post-eof"></div>
        {% else %}
        <div class="post-tags">

            {% for tag in post.tags.all %}
            <a href="{%url 'blog:tag' tag%}" rel="tag"># {{tag }}</a>
            {% endfor %}
            {% if user.is_authenticated %}
            <a href="{{post.get_admin_url}}">编辑</a>
            {% endif %}
        </div>

        <div class="post-nav">
            {% if next_post %}
            <div class="post-nav-next post-nav-item">
                <a href="{{next_post.get_absolute_url}}" rel="next" title="{{next_post.title}}">
                    <i class="fa fa-chevron-left"></i>{{next_post.title}}
                </a>
            </div>
            {% endif %}
            {% if prev_post %}
            <span class="post-nav-divider"></span>
            <div class="post-nav-prev post-nav-item">
                <a href="{{prev_post.get_absolute_url}}" rel="next" title="{{prev_post.title}}">
                    <i class="fa fa-chevron-right"></i> {{prev_post.title}}
                </a>
            </div>
            {% endif %}
        </div>
        {% endif %}

    </footer>
</article>

templates/_macro/reward.html
{% if theme.alipay or theme.wechatpay %}
  <div style="padding: 10px 0; margin: 20px auto; width: 90%; text-align: center;">
    <div>{{ theme.reward_comment }}</div>
    <button id="rewardButton" disable="enable" onclick="var qr = document.getElementById('QR'); if (qr.style.display === 'none') {qr.style.display='block';} else {qr.style.display='none'}">
      <span>赏</span>
    </button>
    <div id="QR" style="display: none;">
      {% if theme.wechatpay %}
        <div id="wechat" style="display: inline-block">
          <img id="wechat_qr" src="{{ theme.wechatpay }}" alt="{{ theme.author }} WeChat Pay"/>
          <p>微信打赏</p>
        </div>
      {% endif %}
      {% if theme.alipay %}
        <div id="alipay" style="display: inline-block">
          <img id="alipay_qr" src="{{ theme.alipay }}" alt="{{ theme.author }} Alipay"/>
          <p>支付宝打赏</p>
        </div>
      {% endif %}
    </div>
  </div>
{% endif %}

templates/_macro/sidebar.html
<div class="sidebar-toggle">
    <div class="sidebar-toggle-line-wrap">
        <span class="sidebar-toggle-line sidebar-toggle-line-first"></span>
        <span class="sidebar-toggle-line sidebar-toggle-line-middle"></span>
        <span class="sidebar-toggle-line sidebar-toggle-line-last"></span>
    </div>
</div>

<aside id="sidebar" class="sidebar" style="margin-top: 294px; display: block;">
    <div class="sidebar-inner">

        <section class="site-overview sidebar-panel {% if not display_toc %} sidebar-panel-active {% endif %}">


            {% if theme.rss %}
            <div class="feed-link motion-element">
                <a href="{{theme.rss }}" rel="alternate">
                    <i class="fa fa-rss"></i>
                    RSS
                </a>
            </div>
            {% endif %}

            <div class="links-of-author motion-element">
                {% for name, value in theme.social.items %}
                <span class="links-of-author-item">
                <a href="{{ value.link }}" target="_blank" title="{{ value.label }}">
                    <i class="fa fa-fw fa-{{ value.social_icons | default:'globe' | lower }}"></i>
                  {{ value.label }}
                </a>
              </span>
                {% endfor %}
            </div>

            {% if theme.creative_commons in cc %}
            <div class="cc-license motion-element" itemprop="license">
                <img src="{{d}}/cc-{{ theme.creative_commons }}.svg" alt="Creative Commons"/>
            </div>
            {% endif %}

            {# Blogroll #}
            {% if theme.links %}
            <div class="links-of-blogroll motion-element {{ s }}">
                <div class="links-of-blogroll-title">
                    <i class="fa  fa-fw fa-{{ theme.links_icon | default:'globe' | lower }}"></i>
                    {{ theme.links_title }}
                </div>
                <ul class="links-of-blogroll-list">
                    {% for name, link in theme.links %}
                    <li class="links-of-blogroll-item">
                        <a href="{{ link }}" title="{{ name }}" target="_blank">{{ name }}</a>
                    </li>
                    {% endfor %}
                </ul>
            </div>
            {% endif %}

        </section>


    </div>
</aside>

templates/_macro/wechat-subscriber.html
{% if theme.wechat_subscriber.enabled %}
<div id="wechat_subscriber" style="display: block; padding: 10px 0; margin: 20px auto; width: 100%; text-align: center">
    <img id="wechat_subscriber_qcode" src="{{ theme.wechat_subscriber.qcode }}" alt="{{ theme.author }} wechat" style="width: 200px; max-width: 100%;"/>
    <div>{{ theme.wechat_subscriber.description }}</div>
</div>
{% endif %}